### PR TITLE
Pagination // fix inappropriate wrapping issue

### PR DESCRIPTION
**Pull request by joe-s-avaya**
[Link to updated Pagination stories](https://deploy-preview-520--neo-react-library-storybook.netlify.app/?path=/docs/components-pagination--docs)
[Link to Figma reference](https://www.figma.com/design/SQHQlIhFHWCjngHZOnK8MH/Web-Components-2.0?node-id=1-133&node-type=CANVAS&t=uIfqt0f9gRhamKNe-0)

**Before tagging the team for a review, I have done the following:**

- [x] run `yarn all` locally: ensures that all tests pass, formatting is done, types pass, and builds pass
- [x] reviewed my code changes
- [x] updated the Deploy Preview link at the top of this PR (or remove it if not applicable)
- [x] updated the Figma referense link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] done an accessibility check on my work (tested with Chrome's `axe Dev Tools`, Mac's VoiceOver, etc.)
- [x] tagged `@avaya-dux/dux-design` if any visual changes have occurred
- [x] tagged `@avaya-dux/dux-devs`

`@avaya-dux/dux-design`: confirm that pagination does not wrap inappropriately when screen is >=808px

`@avaya-dux/dux-devs`: the usual

**EXAMPLE IMAGE(S):**
OLD vs NEW example
Screenshot 2024-09-06 at 13 36 08

Minimum width example
Screenshot 2024-09-06 at 13 44 26

## Summary by CodeRabbit

- **New Features**
	- Enhanced pagination functionality to accommodate larger datasets, improving scalability and performance.
- **Style**
	- Updated CSS rules for pagination controls to ensure navigation elements remain aligned and accessible on larger screens.

### CODE REVIEW

**Review by yangAtSpoken — APPROVED** [review]

**Comment by matthewAvaya** [comment]
At condensed views, some of the text is being wrapped to a new line such as 1-10 / 50 and 1/50 pages (see screenshot below. I prefer if the text and other design elements didn't wrap and instead converted to the condensed version. 
Screen Shot 2024-09-06 at 2 22 25 PM

**Comment by Justin-Avaya** [comment]
Not sure what size @matthewAvaya is referencing above. 

The screenshot attached shows similar results at 808px wide, however it's unclear to me what you mean by "wrap inappropriately" and if this qualifies or not.
Screenshot 2024-09-06 at 3 55 11 PM

 Additionally i'm confused where "808px" is coming from.

**Comment by joe-s-avaya** [comment]
@avaya-dux/dux-design I will show this to you in standup this morning so we can get on the same page about how I determined "808px" and what I should do with this work.

**Review by enrique-prado — APPROVED** [review]

**Comment by joe-s-avaya** [comment]
@avaya-dux/dux-design I've updated the example to work with a window size of as low as 705px (pagination width of 673px) when the page size is in the ten thousands (50k in my example).

Screenshot 2024-09-09 at 15 46 54

**Comment by Justin-Avaya** [comment]
@joe-s-avaya - very slick. If 50,000 items are selected, will this breakpoint accommodate?

**Comment by joe-s-avaya** [comment]
> @joe-s-avaya - very slick. If 50,000 items are selected, will this breakpoint accommodate?

The Pagination does not have any concept of selected items yet. But yes, once I get to implementing that work then yes, it will.

**Review by Justin-Avaya — APPROVED** [review]

**Pull request merged**
