### PR TITLE
Neo-1387 remove placeholder from Select examples

### PR DESCRIPTION
**Pull request by yangAtSpoken**
[Link to updated components in Deploy Preview](https://deploy-preview-108--neo-react-library-storybook.netlify.app/?path=/story/components-select--basic-selects)

**Before tagging the team for a review, I have done the following:**
- [x] reviewed my code changes
- [x] ensured that all tests pass
- [x] updated the link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] tagged Matt if any visual changes have occurred
- [x] done an accessibility check on my work

This PR removed placeholder from Select example; But it is kept and made completely optional.

### CODE REVIEW

**Comment by joe-s-avaya** [comment]
No, don't do this. You're removing a core attribute of the element. Removing default placeholder text? Sure, but saying that we can _never_ use placeholder text? No, that does not make sense to do. There is no a11y recommendation (that I can find) that says to _never_ use placeholder text for a Select.

**Comment by yangAtSpoken** [comment]
> No, don't do this. You're removing a core attribute of the element. Removing default placeholder text? Sure, but saying that we can _never_ use placeholder text? No, that does not make sense to do. There is no a11y recommendation (that I can find) that says to _never_ use placeholder text for a Select.

@matthewAvaya Do you have references @joe-s-avaya is asking here?

**Comment by matthewAvaya** [comment]
I'm trying to find the source, but I know we've talked with Terri on placeholder text as it's confusing for people with cognitive issues. I can't recall if this only applies to text inputs but I thought it also would apply to search and select components. I've emailed Terri for her input. In the meantime, I found this link on W3 regarding [placeholder text](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research#:~:text=Placeholder%20text%20within%20a%20form,with%20visual%20and%20cognitive%20impairments.).

**Comment by joe-s-avaya** [comment]
> I'm trying to find the source, but I know we've talked with Terri on placeholder text as it's confusing for people with cognitive issues. I can't recall if this only applies to text inputs but I thought it also would apply to search and select components. I've emailed Terri for her input. In the meantime, I found this link on W3 regarding [placeholder text](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research#:~:text=Placeholder%20text%20within%20a%20form,with%20visual%20and%20cognitive%20impairments.).

@matthewAvaya + @yangAtSpoken, yes, as I recall from our discussions with Terri, her statement was that placeholder text should not be used _instead of_ good labels. Her concern was that placeholder text would be used instead of labeling the input (eg, "First Name", "Password", ect.) or informational labels (eg, our "helper text", such as "Password must be 8 characters long", "Postal Code format: #####-####", ect.).

But, with all of that said, placeholder text can still be useful to give users an idea of what the result may look like, or to give information such as "click here to select your state".

**Comment by matthewAvaya** [comment]
Including a 'placeholder result' may look like something was already chosen. For additional instructions, it should be applied to the label or as a helper text. We can pause on this specific issue until Terri responds and confirms.

**Comment by matthewAvaya** [comment]
Here's Terri's response regarding placeholder text...

_Hi Matt, it’s not that it doesn’t need a placeholder text. You’re allowed to use placeholder text as long as it’s not the accessibility label for the field. Also, it must have color contrast if there is a permanent fixed label and the placeholder text accompanies the label with additional information then it’s fine._

I would still argue it's better to not have any placeholder text if it can be avoided, and that can be a design decision.

**Review by enrique-prado — APPROVED** [review]

**Comment by joe-s-avaya** [comment]
based on discussion from this morning, recommend closing this PR and marking associated ticket as "won't do"

**Review by matthewAvaya — APPROVED** [review]

**Review by joe-s-avaya — APPROVED** [review]
thanks for tagging me on this, good changes 👍

**Pull request merged**
