### PR TITLE
vertically center notification text when there is only the title or description 

### PR DESCRIPTION
**Pull request by joe-s-avaya**
[Link to updated Notifications stories](https://deploy-preview-409--neo-react-library-storybook.netlify.app/?path=/story/components-notification--content-variants)

**Before tagging the team for a review, I have done the following:**
- [x] reviewed my code changes
- [x] ensured that all tests pass
- [x] updated the link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] tagged Matt if any visual changes have occurred
- [x] done an accessibility check on my work

@avaya-dux/dux-design: this 👇  is what [you are asking for](https://github.com/avaya-dux/neo-react-library/pull/407#issuecomment-2140943027) yes?

Screenshot 2024-05-31 at 09 17 44

## Summary by CodeRabbit

- **Style**
  - Improved layout and alignment of notification messages by updating the notification styles.

### CODE REVIEW

**Comment by matthewAvaya** [comment]
Yes, exactly. That looks great.

**Comment by joe-s-avaya** [comment]
> It would be good to get an example of a notification with a single row of text that wraps to multiple lines of text as it becomes responsive to a smaller size.

@matthewAvaya you could just make the screen smaller. I'm hesitant to add more examples when we already have so many of them. It already feels like an overload of information.

**Comment by Justin-Avaya** [comment]
@matthewAvaya - I think i've been able to show an example of what you were hoping to see without the teaming needing to have the dev team create another example for the story.

I think it's looking as we were hoping for. Both the title and the body correctly truncate after two lines.

Screenshot 2024-05-31 at 8 41 37 AM

**Review by Justin-Avaya — APPROVED** [review]

**Review by matthewAvaya — APPROVED** [review]
Nice. I was able to see the single line of text respond to multiple lines and it looks good.

**Pull request merged**
