### PR TITLE
NEO-1845-part2: place menu by the side of the toggle

### PR DESCRIPTION
**Pull request by yangAtSpoken**
[Link to updated components in Deploy Preview](https://deploy-preview-270--neo-react-library-storybook.netlify.app/?path=/story/components-menu--simple-menu)

**Before tagging the team for a review, I have done the following:**
- [x] reviewed my code changes
- [x] ensured that all tests pass
- [x] updated the link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] tagged Matt if any visual changes have occurred
- [x] done an accessibility check on my work

* position menu side by side with the toggle button
* allow menu to expand upwards when space is limited

### CODE REVIEW

**Review by mrazian85 — APPROVED** [review]
Stories look/work good, you have tests for the new logic, and your CSS classes are well-named. LGTM 👍

**Comment by matthewAvaya** [comment]
- After clicking the ESC key to close an opened dropdown menu, the focus should return to the button. Currently, I have to click on the SHIFT+TAB keys to make the focus return to the original button. 
- Using the screen reader, when the focus is on the first menu item, it reads 'Menu Item 1. Menu item. Menu 3 items.' It would be better to read it as 'Menu Item 1 not selected. One of three.'

**Comment by yangAtSpoken** [comment]
> * After clicking the ESC key to close an opened dropdown menu, the focus should return to the button. Currently, I have to click on the SHIFT+TAB keys to make the focus return to the original button.
> * Using the screen reader, when the focus is on the first menu item, it reads 'Menu Item 1. Menu item. Menu 3 items.' It would be better to read it as 'Menu Item 1 not selected. One of three.'

@matthewAvaya 'ESC' problem fixed. As for the announcement, the default reading makes more sense.  And we do not a lot of options to control what VoiceOver announces.

**Comment by matthewAvaya** [comment]
> > * After clicking the ESC key to close an opened dropdown menu, the focus should return to the button. Currently, I have to click on the SHIFT+TAB keys to make the focus return to the original button.
> > * Using the screen reader, when the focus is on the first menu item, it reads 'Menu Item 1. Menu item. Menu 3 items.' It would be better to read it as 'Menu Item 1 not selected. One of three.'
> 
> @matthewAvaya 'ESC' problem fixed. As for the announcement, the default reading makes more sense. And we do not a lot of options to control what VoiceOver announces.

Okay, sounds good. I'll approve.

**Review by matthewAvaya — APPROVED** [review]

**Pull request merged**
