### PR TITLE
NEO-2280 // Pagination update part 2, update Select

### PR DESCRIPTION
**Pull request by joe-s-avaya**
[Link to default Table story](https://deploy-preview-499--neo-react-library-storybook.netlify.app/?path=/story/components-table--default)
[Link to Figma reference](https://www.figma.com/design/SQHQlIhFHWCjngHZOnK8MH/Web-Components-2.0?node-id=1-133&t=PAQBk5rXYeVwh6bb-0)

**Before tagging the team for a review, I have done the following:**

- [x] run `yarn all` locally: ensures that all tests pass, formatting is done, types pass, and builds pass
- [x] reviewed my code changes
- [x] updated the Deploy Preview link at the top of this PR (or remove it if not applicable)
- [x] updated the Figma referense link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] done an accessibility check on my work (tested with Chrome's `axe Dev Tools`, Mac's VoiceOver, etc.)
- [x] tagged `@avaya-dux/dux-design` if any visual changes have occurred
- [x] tagged `@avaya-dux/dux-devs`

This PR updates the Pagination Select to be our Neo branded one.

Screenshot 2024-08-19 at 09 50 10

`@avaya-dux/dux-design`: Review Pagination "Rows" Select the appropriate look and feel.

`@avaya-dux/dux-devs`:

- Review code for any potential Issues.
- I had to adjust Pagination implementations as our `Select` does not return an event, just the data. This does not appear to matter for any implementation, but it does make this PR annoyingly complex.
- Note that I have added quite a bit of CSS. I will be moving that to the CSS Library... eventually.

## Summary by CodeRabbit

- **New Features**
	- Introduced a custom dropdown for selecting the number of items per page, enhancing user experience with improved styling and functionality.
	- Added new CSS for pagination to improve layout and visual consistency.
  
- **Bug Fixes**
	- Simplified event handling in pagination components by removing unnecessary parameters, enhancing clarity and streamlining functionality.

- **Tests**
	- Updated tests to reflect changes in pagination logic and user interaction methods, ensuring accurate validation of the component's behavior.

### CODE REVIEW

**Comment by matthewAvaya** [comment]
Add an extra padding of 4px between the number and the chevron icon.

**Comment by joe-s-avaya** [comment]
@matthewAvaya updated from `4px` to `8px`

**Review by matthewAvaya — APPROVED** [review]

**Review by Justin-Avaya — APPROVED** [review]
The dropdown menu has keyboard focus at the same time as the select component.
out of scope? you can decide.

Screenshot 2024-08-19 at 12 54 51 PM

**Comment by joe-s-avaya** [comment]
> The dropdown menu has keyboard focus at the same time as the select component. out of scope? you can decide.

**Review by yangAtSpoken — APPROVED** [review]
Could have used some css nesting  in the shim file.  Since there are future work on the CSS library side, what we have is fine.   Glad to have the native Select replaced. Yeah!

**Comment by joe-s-avaya** [comment]
> The dropdown menu has keyboard focus at the same time as the select component. out of scope? you can decide.


Noted, but not worrying about that for this PR 👍

**Pull request merged**
