### PR TITLE
NEO-2280 // update Pagination button styling

### PR DESCRIPTION
**Pull request by joe-s-avaya**
[Link to Table component](https://deploy-preview-514--neo-react-library-storybook.netlify.app/?path=/story/components-table--server-side-pagination)
[Link to Figma reference](https://www.figma.com/design/SQHQlIhFHWCjngHZOnK8MH/Web-Components-2.0?node-id=6170-2353&node-type=FRAME&t=vKfAZHlPYaQSXf6V-0)

**Before tagging the team for a review, I have done the following:**

- [x] run `yarn all` locally: ensures that all tests pass, formatting is done, types pass, and builds pass
- [x] reviewed my code changes
- [x] updated the Deploy Preview link at the top of this PR (or remove it if not applicable)
- [x] updated the Figma referense link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] done an accessibility check on my work (tested with Chrome's `axe Dev Tools`, Mac's VoiceOver, etc.)
- [x] tagged `@avaya-dux/dux-design` if any visual changes have occurred
- [x] tagged `@avaya-dux/dux-devs`

Updating Pagination buttons styling (no functional changes). Arrow buttons are now chevrons, numbered buttons are now "primary" instead of "secondary" styling, and they are all slightly smaller. 

`@avaya-dux/dux-design`: Review Pagination Button styling updates

- arrow buttons are now chevrons
- number buttons are now blue (primary) instead of white (secondary)
- arrow and number buttons are 32x32
- OUT OF SCOPE: "..." button/menu thingy, that will be a future PR, it remains three dots for now

`@avaya-dux/dux-devs`: test and review code quality

## Summary by CodeRabbit

- **New Features**
	- Updated the pagination button styles to enhance visual feedback for the current page.
	- Introduced new CSS styles for improved consistency in pagination component appearance and layout.

- **Bug Fixes**
	- Corrected button class names for navigation arrows to align with updated design standards.

- **Tests**
	- Adjusted test files to reflect changes in button styling for selected pages, ensuring accurate representation in tests.

### CODE REVIEW

**Review by enrique-prado — APPROVED** [review]

**Comment by Justin-Avaya** [comment]
1) per the spec, the arrow buttons are not 32x32, they are 24x32. 
example



2) pagination buttons, arrows, etc area jumps around when selecting another page. nauseating after a while.
example

**Review by yangAtSpoken — APPROVED** [review]

**Comment by joe-s-avaya** [comment]
@Justin-Avaya 

> 1. per the spec, the arrow buttons are not 32x32, they are 24x32.

Updated to have proper width and have a 4px margin. 

> 2. pagination buttons, arrows, etc area jumps around when selecting another page. nauseating after a while.

Working on a fix.

**Review by matthewAvaya — APPROVED** [review]

**Comment by joe-s-avaya** [comment]
> @Justin-Avaya
> 
> > 1. per the spec, the arrow buttons are not 32x32, they are 24x32.
> 
> Updated to have proper width and have a 4px margin.
> 
> > 2. pagination buttons, arrows, etc area jumps around when selecting another page. nauseating after a while.
> 
> Working on a fix.

2 has been updated, please review.

Note that the button width issue has _not_ been fixed. That will be done in another story.

**Comment by Justin-Avaya** [comment]
As noted verbally in our stand up, the button width for pages with 4+ characters is incorrect. 
Just documenting this observation as it was declared out of scope for this PR.

Example
Screenshot 2024-09-04 at 1 13 36 PM

**Review by Justin-Avaya — APPROVED** [review]

**Pull request merged**
