### PR TITLE
Storybook // add mode and dir to global options

### PR DESCRIPTION
**Pull request by joe-s-avaya**
[Link to Icon stories](https://deploy-preview-583--neo-react-library-storybook.netlify.app/?path=/docs/components-icon--docs)

**Before tagging the team for a review, I have done the following:**

- [x] run `yarn all` locally: ensures that all tests pass, formatting is done, types pass, and builds pass
- [x] reviewed my code changes
- [x] updated the Deploy Preview link at the top of this PR (or remove it if not applicable)
- [x] updated the Figma referense link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] done an accessibility check on my work (tested with Chrome's `axe Dev Tools`, Mac's VoiceOver, etc.)
- [x] tagged `@avaya-dux/dux-design` if any visual changes have occurred
- [x] tagged `@avaya-dux/dux-devs`

Adding two global options to Storybook.
- `mode` for setting light/dark
- `dir` for ltr/rtl

**IMPORTANT**: Yes I know that there is an ugly white border when in dark mode. I spent a bunch of time trying to get rid of it and got annoyed. If it's a big deal to someone, I'll fix it in a future PR, but IMO it's not important enough to spend more time on.

**_Devs:_** This is largely inspired by these two Chromatic videos ([Dark Mode in Storybook](https://www.youtube.com/watch?v=FVg9eWQsUbU), [Create custom toolbar items using global types](https://www.youtube.com/watch?v=DuJ_gmSncLM)). I highly recommend watching them, they're super informative about Storybook functionality, and are concise.

`@avaya-dux/dux-design`: just tell me that you understand how to use the two new buttons

`@avaya-dux/dux-devs`

- the usual
- NOTE: I removed `preview.ts` and replaced it with `preview.tsx` so that I could add the Storybook decorators (which is what allows all this to work)

**EXAMPLE FUNCTIONALITY GIF:**

## Summary by CodeRabbit

- **New Features**
	- Introduced a new CSS class `.preview-story-wrapper` for improved styling in Storybook.
	- Added global configuration for Storybook previews, including support for light/dark modes and text direction.
  
- **Bug Fixes**
	- Streamlined the `Icon` component stories by removing unnecessary properties and simplifying the structure for better clarity and presentation.

- **Refactor**
	- Updated the structure of story definitions for the `Icon` component, enhancing readability and maintainability.

### CODE REVIEW

**Review by enrique-prado — APPROVED** [review]
Nice work

**Review by matthewAvaya — APPROVED** [review]
Nice, I like it.

**Review by Justin-Avaya — APPROVED** [review]
Understood. Nice work.

**Review by yangAtSpoken — APPROVED** [review]
Nice work. Glad Storybook makes it easy to extend its functionalities.

**Pull request merged**
