### PR TITLE
NE0-2326: Drawer final visual details

### PR DESCRIPTION
**Pull request by enrique-prado**
[Link to Drawer](https://deploy-preview-484--neo-react-library-storybook.netlify.app/?path=/story/components-drawer--with-scrollbar))
[Link to Figma reference](https://www.figma.com/design/RaolSZnCfBqOYkbjaWvLc0/Neo-UX-Projects-FY24---v2?node-id=4154-56892&m=dev)

**Before tagging the team for a review, I have done the following:**

- [x] run `yarn all` locally: ensures that all tests pass, formatting is done, types pass, and builds pass
- [x] reviewed my code changes
- [x] updated the Deploy Preview link at the top of this PR (or remove it if not applicable)
- [x] updated the Figma referense link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] tagged `@avaya-dux/dux-design` if any visual changes have occurred
- [x] tagged `@avaya-dux/dux-devs`

This PR finalizes the last visual details for the Drawer component and makes the component public for consumption inside the Neo React library.

`@avaya-dux/dux-design`: Verify the following visuals.

- Line separators for header and footer sections match Figma designs.
-  Paddings in Header and Footers match Figma designs.
- Padding between buttons in footer should match Figma (8px)
- "not in scope" Ignore hover state on close button. I will create a new Jira ticket for this since it's not an easy fix.
- "not in scope" You have already reviewed functionality and other visuals. I didn't make any changes since your last review.

`@avaya-dux/dux-devs`: No functionality changes. Just visual tweaks.

image

## Summary by CodeRabbit

- **New Features**
	- Improved responsiveness of the drawer component for better usability across devices.
	- Enhanced visual consistency with updated border colors and increased padding in the header.
	- Added export for the Drawer component to streamline imports in the application.

- **Style**
	- Adjusted styling to align the drawer's appearance with overall aesthetics and usability.

### CODE REVIEW

**Review by joe-s-avaya — APPROVED** [review]
LGTM 👍 
Now that the drawer is complete, please move the CSS into neo-css. You can create a new ticket for this work if you'd like, but we must to support this in both libraries.

**Comment by joe-s-avaya** [comment]
That's a really nice css transition!

**Comment by joe-s-avaya** [comment]
a11y violation, this doesn't need to be fixed in this PR, but it does need to be fixed
Screenshot 2024-08-02 at 09 27 34

**Review by yangAtSpoken — APPROVED** [review]

**Review by Justin-Avaya — APPROVED** [review]

**Comment by matthewAvaya** [comment]
- When I first open the drawer, the clear icon (X) has a light gray background. This should only be on hover state. 
Screen Shot 2024-08-02 at 11 21 21 AM

- When I resize the height of the browser, there is a small gap at the bottom of the drawer before resizing it to flush to the bottom of the browser. It should always be connected without any gap. 

- Can we replace the bottom actions with a secondary and primary button instead of a form field as that is a real use case? 
Screen Shot 2024-08-02 at 11 30 48 AM


Accessibility issues:
- Scrollable region must have keyboard access for the user to scroll - https://axe.deque.com/issues/19b591d2-e2e0-480a-97a1-736cd3dd0add

**Pull request merged**
