### PR TITLE
NEO-2189  The dragged row now moves by one row at each key press

### PR DESCRIPTION
**Pull request by yangAtSpoken**
[Link to updated components in Deploy Preview](https://deploy-preview-469--neo-react-library-storybook.netlify.app/?path=/story/components-table--editable-data)

**Before tagging the team for a review, I have done the following:**

- [x] run `yarn all` locally: ensures that all tests pass, formatting is done, types pass, and builds pass
- [x] reviewed my code changes
- [x] updated the link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [ ] done an accessibility check on my work (tested with Chrome's `axe Dev Tools`, Mac's VoiceOver, etc.)
- [x] tagged `@avaya-dux/dux-design` if any visual changes have occurred
- [x] tagged `@avaya-dux/dux-devs`

`@avaya-dux/dux-design`: per @matthewAvaya suggestion, changed keyboard movement from 25px default to one row per key press.

`@avaya-dux/dux-devs`:  minor change

## Summary by CodeRabbit

- **New Features**
	- Improved keyboard navigation for drag-and-drop operations within the Table component.
	- Enhanced accuracy in coordinate calculations for sortable items.

- **Bug Fixes**
	- Addressed issues with keyboard interactions to ensure a smoother user experience.

### CODE REVIEW

**Review by joe-s-avaya — APPROVED** [review]
nice

**Review by matthewAvaya — APPROVED** [review]
Showed this to Jenn and she likes it. Nice job @yangAtSpoken

**Comment by yangAtSpoken** [comment]
@Justin-Avaya Can I have your approval, please?

**Comment by Justin-Avaya** [comment]
@yangAtSpoken - the only issue i am struggling with is where the focused is placed after dropping the row. I was expecting the last item dropped would receive focus whereas the first item in the table seems to be placed in focus instead.

If this is expected, then approved. Just let me know.

See example:

**Comment by yangAtSpoken** [comment]
> @yangAtSpoken - the only issue i am struggling with is where the focused is placed after dropping the row. I was expecting the last item dropped would receive focus whereas the first item in the table seems to be placed in focus instead.
> 
> If this is expected, then approved. Just let me know.
> 
> See example:  [  ](https://private-user-images.githubusercontent.com/161497909/351446934-67f6da9d-37f5-4be2-9415-ee234ab460d3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTk2NDMsIm5iZiI6MTcyMTc1OTM0MywicGF0aCI6Ii8xNjE0OTc5MDkvMzUxNDQ2OTM0LTY3ZjZkYTlkLTM3ZjUtNGJlMi05NDE1LWVlMjM0YWI0NjBkMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxODI5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2I4NGIxMjUyOWY4ODZkMWZhNTY3NWUyNmIwNTEyZDNhZTE3MWExNjUyYzM5MGNlMTZlYTJjMTU4OWJmZTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bQmvjuf7lqwWsg7bORe-LiMXrjI-sejiUyAHUbp2asY) [ ](https://private-user-images.githubusercontent.com/161497909/351446934-67f6da9d-37f5-4be2-9415-ee234ab460d3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTk2NDMsIm5iZiI6MTcyMTc1OTM0MywicGF0aCI6Ii8xNjE0OTc5MDkvMzUxNDQ2OTM0LTY3ZjZkYTlkLTM3ZjUtNGJlMi05NDE1LWVlMjM0YWI0NjBkMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxODI5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2I4NGIxMjUyOWY4ODZkMWZhNTY3NWUyNmIwNTEyZDNhZTE3MWExNjUyYzM5MGNlMTZlYTJjMTU4OWJmZTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bQmvjuf7lqwWsg7bORe-LiMXrjI-sejiUyAHUbp2asY)

Hi @Justin-Avaya Keyboard focus is managed by the Drag and Drop library and it goes back to the same row position where the drag started.  If you started dragging at the 2nd row, focus will return to the 2nd row when the drag ends.  This can not be customized right now and it is out of the scope of this PR.  Please approve.  Thx.

**Review by Justin-Avaya — APPROVED** [review]

**Pull request merged**
